const skills=[['HTML / CSS',72],['JavaScript',65],['UI & UX thinking',62],['Dati e logica',55],['Automazione',52],['Testing',42]];
document.querySelector('#skillList').innerHTML=skills.map(([n,v])=>`<div class="skill"><div class="skill-head"><span>${n}</span><span>${v}/100 · ${v>=70?'Autonomo':v>=55?'Operativo':'In crescita'}</span></div><div class="track"><i data-width="${v}%"></i></div></div>`).join('');
setTimeout(()=>document.querySelectorAll('.track i').forEach(x=>x.style.width=x.dataset.width),250);
const rc=document.querySelector('#radar'),rx=rc.getContext('2d'),cx=260,cy=205,R=140,N=skills.length;rx.font='12px DM Mono';rx.textAlign='center';for(let ring=1;ring<=4;ring++){rx.beginPath();for(let i=0;i<N;i++){const a=-Math.PI/2+i*2*Math.PI/N,x=cx+Math.cos(a)*R*ring/4,y=cy+Math.sin(a)*R*ring/4;i?rx.lineTo(x,y):rx.moveTo(x,y)}rx.closePath();rx.strokeStyle='#33443b';rx.stroke()}rx.beginPath();skills.forEach(([n,v],i)=>{const a=-Math.PI/2+i*2*Math.PI/N,x=cx+Math.cos(a)*R*v/100,y=cy+Math.sin(a)*R*v/100;i?rx.lineTo(x,y):rx.moveTo(x,y);const lx=cx+Math.cos(a)*(R+34),ly=cy+Math.sin(a)*(R+25);rx.fillStyle='#a9b5ae';rx.fillText(n.split(' ')[0],lx,ly)});rx.closePath();rx.fillStyle='#c9ff4a33';rx.fill();rx.strokeStyle='#c9ff4a';rx.lineWidth=2;rx.stroke();

// Survival game
const gc=document.querySelector('#game'),g=gc.getContext('2d'),keys=new Set();let running=false,score=0,frame=0,player,shots,drones;
function resetGame(){score=0;frame=0;player={x:355,y:340,vx:0,vy:0,w:34,h:44};shots=[];drones=[];document.querySelector('#score').textContent='0000'}
function spawn(){drones.push({x:20+Math.random()*700,y:-30,vy:1.4+score/1500,w:42,h:22})}
function gameLoop(){if(!running)return;frame++;if(frame%70===0)spawn();player.vx=(keys.has('ArrowLeft')||keys.has('KeyA')?-4:0)+(keys.has('ArrowRight')||keys.has('KeyD')?4:0);if((keys.has('KeyW')||keys.has('ArrowUp'))&&player.y>=339)player.vy=-9;player.vy+=.45;player.x=Math.max(0,Math.min(gc.width-player.w,player.x+player.vx));player.y=Math.min(340,player.y+player.vy);if(player.y===340)player.vy=0;if(keys.has('Space')&&frame%9===0)shots.push({x:player.x+15,y:player.y,vy:-8});shots.forEach(s=>s.y+=s.vy);drones.forEach(d=>d.y+=d.vy);for(let d of drones)for(let s of shots)if(s.x>d.x&&s.x<d.x+d.w&&s.y>d.y&&s.y<d.y+d.h){d.dead=s.dead=true;score+=100}drones=drones.filter(d=>!d.dead&&d.y<430);shots=shots.filter(s=>!s.dead&&s.y>-10);if(drones.some(d=>d.y+d.h>player.y&&d.x<player.x+player.w&&d.x+d.w>player.x)){running=false;draw();g.fillStyle='#14211cdd';g.fillRect(190,145,380,120);g.fillStyle='white';g.textAlign='center';g.font='700 24px Manrope';g.fillText('GAME OVER',380,195);g.font='14px DM Mono';g.fillText(`Punteggio ${score} — premi Avvia`,380,225);return}document.querySelector('#score').textContent=String(score).padStart(4,'0');draw();requestAnimationFrame(gameLoop)}
function draw(){g.clearRect(0,0,760,420);g.fillStyle='#bde6ef';g.fillRect(0,0,760,360);g.fillStyle='#eef7d0';g.beginPath();g.arc(650,70,35,0,Math.PI*2);g.fill();g.fillStyle='#769958';g.fillRect(0,384,760,36);g.fillStyle='#5e8247';g.fillRect(0,378,760,8);g.fillStyle='#ed493d';g.fillRect(player.x,player.y,player.w,player.h);g.fillStyle='#14211c';g.fillRect(player.x+6,player.y+9,7,7);g.fillRect(player.x+21,player.y+9,7,7);g.fillStyle='#fff089';shots.forEach(s=>g.fillRect(s.x,s.y,4,12));drones.forEach(d=>{g.fillStyle='#293b35';g.fillRect(d.x,d.y,d.w,d.h);g.fillStyle='#ff6b5e';g.fillRect(d.x+17,d.y+8,8,5);g.fillStyle='#293b35';g.fillRect(d.x-10,d.y+3,62,3)})}
resetGame();draw();document.querySelector('#startGame').onclick=()=>{resetGame();running=true;gc.focus();gameLoop()};addEventListener('keydown',e=>{if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();keys.add(e.code)});addEventListener('keyup',e=>keys.delete(e.code));document.querySelectorAll('[data-key]').forEach(b=>{const k=b.dataset.key;b.onpointerdown=()=>keys.add(k);b.onpointerup=()=>keys.delete(k)});

// Bank demo — synthetic in-memory dataset
const customers=[{id:'CL-1042',name:'Marco Riva',city:'Milano',balance:42850,invest:18700,mortgage:122000,risk:'Basso'},{id:'CL-1078',name:'Sara Conti',city:'Torino',balance:12340,invest:5600,mortgage:0,risk:'Basso'},{id:'CL-1115',name:'Luca Serra',city:'Roma',balance:2840,invest:0,mortgage:196000,risk:'Alto'},{id:'CL-1191',name:'Elena Villa',city:'Bergamo',balance:27500,invest:42000,mortgage:68000,risk:'Medio'},{id:'CL-1224',name:'Paolo Greco',city:'Napoli',balance:-1250,invest:0,mortgage:84000,risk:'Alto'},{id:'CL-1308',name:'Giulia Neri',city:'Bologna',balance:58700,invest:76100,mortgage:0,risk:'Basso'}];
const money=n=>new Intl.NumberFormat('it-IT',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(n);function renderBank(list=customers){document.querySelector('#bankRows').innerHTML=list.map(c=>`<tr><td><b>${c.name}</b><br><small>${c.id} · ${c.city}</small></td><td>${money(c.balance)}</td><td>${money(c.invest)}</td><td>${money(c.mortgage)}</td><td><span class="risk ${c.risk}">${c.risk}</span></td></tr>`).join('')||'<tr><td colspan="5">Nessun cliente trovato.</td></tr>';const exposure=list.reduce((s,c)=>s+c.mortgage,0),assets=list.reduce((s,c)=>s+c.balance+c.invest,0),alerts=list.filter(c=>c.risk==='Alto').length;document.querySelector('#bankKpis').innerHTML=`<div><span>Patrimonio gestito</span><b>${money(assets)}</b></div><div><span>Esposizione mutui</span><b>${money(exposure)}</b></div><div><span>Alert rischio</span><b>${alerts}</b></div>`}renderBank();document.querySelector('#bankForm').onsubmit=e=>{e.preventDefault();const q=document.querySelector('#bankSearch').value.toLowerCase(),r=document.querySelector('#riskFilter').value;renderBank(customers.filter(c=>(c.name+' '+c.city+' '+c.id).toLowerCase().includes(q)&&(r==='all'||c.risk===r)))};

// Robot cell state machine
const cell=document.querySelector('.factory'),state=document.querySelector('#cellState'),light=document.querySelector('#cellLight'),log=document.querySelector('#ioLog'),countEl=document.querySelector('#boxCount');let cellRun=false,count=0,timer;
function validIO(){return ['ioGuard','ioBelts','ioPallet'].every(id=>document.querySelector('#'+id).checked)}function setState(s,msg){state.textContent=s;light.style.background=s==='RUNNING'?'#7be6a9':'#ff6b5e';log.textContent=`[${new Date().toLocaleTimeString('it-IT')}] ${msg}`}
function cycle(){if(!cellRun)return;if(!validIO()){cellRun=false;cell.classList.remove('running');clearInterval(timer);setState('WAIT I/O','Sequenza sospesa: verificare riparo, nastri e pallet.');return}count++;const b=document.createElement('i');b.className='box';b.style.left=`${(count-1)%3*35+4}px`;b.style.bottom=`${18+Math.floor((count-1)/3)*27}px`;document.querySelector('#pallet').appendChild(b);countEl.textContent=`Pallet ${count} / 6`;setState('RUNNING',`Box ${count} depositato. Conferma PLC ricevuta.`);if(count===6){cellRun=false;clearInterval(timer);cell.classList.remove('running');setState('AMR CALL','Pallet completo. Richiesto prelievo al muletto AMR.');document.querySelector('#forklift').classList.add('pickup');setTimeout(()=>{document.querySelector('#pallet').innerHTML='';document.querySelector('#forklift').classList.remove('pickup');count=0;countEl.textContent='Pallet 0 / 6';setState('READY','Pallet vuoto disponibile. Cella pronta al riavvio.')},3000)}}
document.querySelector('#toggleCell').onclick=()=>{if(cellRun){cellRun=false;clearInterval(timer);cell.classList.remove('running');setState('STOPPED','Arresto operatore.')}else if(validIO()){cellRun=true;cell.classList.add('running');setState('RUNNING','START accettato. Sequenza automatica attiva.');timer=setInterval(cycle,1400)}else setState('WAIT I/O','START rifiutato: segnali I/O incompleti.')};['ioGuard','ioBelts','ioPallet'].forEach(id=>document.querySelector('#'+id).onchange=()=>{if(cellRun&&!validIO())cycle()});document.querySelector('#year').textContent=new Date().getFullYear();
